### PR TITLE
Decode Morse message

### PR DESCRIPTION
**Pull request by Bupilipili**
### Decode a Morse code message
- [x] Created the repo
- [x] Installed the linters
- [x] Installed necessary gems
- [x] Added the hash for morse codes
- [x] Added the methods for decoding (decode_char, decode_word, decode)
- [x] Created the README

### CODE REVIEW

**Comment by topeogunleye** [comment]
Hi @Bupilipili, @Ochiengsteven, @fatima-najafi, 

I am your code reviewer, and I need you to please kindly add Future Features section to your README file.

**Comment by fatima-najafi** [comment]
> Hi @Bupilipili, @Ochiengsteven, @fatima-najafi,
> 
> I am your code reviewer, and I need you to please kindly add Future Features section to your README file.

**Comment by topeogunleye** [comment]
why did you close the branch @fatima-najafi. please revert

**Review by topeogunleye — APPROVED** [review]
Hi @Bupilipili, @Ochiengsteven, @fatima-najafi, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

dwayne-the-rock

## (Highlights) Good Points: 💪 

1. **Meaningful Method Names:**
   - Your `#decode_char` and `#decode_word` methods are named appropriately, providing clear insights into their functionality. Naming is crucial in code readability, and you've nailed it! 📘

2. **Optimal Use of Dictionary:**
   - Your utilization of a dictionary (most likely a hash) for Morse code char symbols is clever and efficient. 🕵️ It makes the translation of Morse code symbols into letters effective and straightforward.

3. **Effective Translation & Decoding:**
   - Your methods successfully translate and decode Morse code symbols, words, and sentences as expected, returning the correct English counterparts. 🌐 

4. **DRY Principle Adherence:**
   - You've excellently reused the `#decode_char` method in `#decode_word` and `#decode_word` in `#decode`, ensuring your code is DRY (Don’t Repeat Yourself), concise, and clean. 🚀

5. **Accurate Output:**
   - Your project produces accurate results as per the requirements. Here are the test results:
     ```ruby
     "A"
     "MY"
     "MY NAME"
     "A BOX FULL OF RUBIES"
     ```

6. **Successful Decoding:**
   - Running the given lines of code in `morse.rb` with `ruby morse.rb` indeed confirmed the correct functioning of your methods. It's fantastic to see the translation working seamlessly! 🎉

### 🎈 **Conclusion:**
Congratulations, @Bupilipili!, @Ochiengsteven, @fatima-najafi, You've done a splendid job with this project, showcasing your understanding of methods, dictionaries, and the DRY principle in Ruby. Keep up the excellent work, and continue coding and exploring! 💻 🌍

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

You can also consider:
- For future pull requests, please notice that your branch name `MorseCodeDecoder` does not follow the convention of being named after a feature or action. For example, you could name your branch `added-MorseCodeDecoder`. This makes it easier to track the changes and the purpose of each branch.
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @topeogunleye in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by topeogunleye** [comment]
@Bupilipili, @fatima-najafi, @Ochiengsteven. "You are welcome to close your pull request whenever you are ready. 👍 Thank you!"

**Pull request merged**
